### PR TITLE
Fix bugs and implement one feature

### LINKED ISSUE #43: DataTables warning when Time column is hidden
Whenever I set the Time column type as Hidden...

I get this error, that shows up constantly

### PR DESCRIPTION
**Pull request by jmp0x00**
Fixed #43 #8 bugs. Implemented #18 feature.
Also, fixed some colorizing problems.

### CODE REVIEW

**Comment by briangann** [comment]
will check this PR out now and see if it can be merged

**Comment by justsans** [comment]
Would you be merging this pull request soon? It looks like this version has fixed some of the major issues with Grafana 6 compatability and is working for me.

**Comment by DawnFreeze** [comment]
Really looking forward to this update

**Comment by briangann** [comment]
will take a look today :)

**Pull request merged**
