### PR TITLE
FEAT: Implemented column filter option

### PR DESCRIPTION
**Pull request by iruizr7**
Implemented per column filters, controlled by a switch.

Fixes https://github.com/briangann/grafana-datatable-panel/issues/66

### CODE REVIEW

**Comment by iruizr7** [comment]
The failed check is not my fault, or I am doing something wrong? It seems CI tried to upload coverage data to Codeclimate and failed because of a faulty token.

**Comment by robertknorton** [comment]
How do I get this in my Grafana instance? I have done the install of Datatable plugin using the Grafana instructions for CLI installation through Docker. I don't seem to have per column searching.

**Comment by iruizr7** [comment]
`grafana-cli --pluginUrl https://github.com/Purpleblobsl/grafana-datatable-panel/releases/download/v1.0.2/grafana-datatable-panel.zip plugins install briangann-datatable-panel`

**Comment by robertknorton** [comment]
Out of curiosity, do I need to uninstall the normal plugin before installing this version or will it automatically overwrite the normal one?

**Comment by robertknorton** [comment]
> `grafana-cli --pluginUrl https://github.com/Purpleblobsl/grafana-datatable-panel/releases/download/v1.0.2/grafana-datatable-panel.zip plugins install briangann-datatable-panel`

I ran this command. Restarted my Grafana instance and it still is not showing a switch to enable per column filtering. Is there something I am missing?

**Comment by robertknorton** [comment]
Okay, I tried updating my original plugin install that didnt work.  I then tried just installing straight and that didnt work. I had to completely remove initial plugin, restart Grafana, install your plugin, then restart Grafana a final time. Now it works.

By any chance were you or are you able to add a search delimiter to enable multi-item searches.
Example: I want to search a column for values of "cat" and "dog" I could type in the search box the following "cats;dog". Where the ";" is the delimiter or some other special character less likely to be used.

**Pull request merged**
